### ISSUE TITLE
Make clear and reset optional

### ISSUE THREAD

**Issue by superhighfives** [superhighfives/sandpit#14]
Not sure if this is necessary, but might be good to allow clear and reset to be toggled on or off—currently they are automatically there if settings are enabled, which is weird for some demos.

**Comment by superhighfives** [comment]
Been thinking, maybe `clear`, `reset`, `fullscreen` and `seed` could be special options _if_ they don't have a value object? Could throw a warning, too.

```
sandpit.settings = {
  normalSetting: {value: 'something'},
  clear: false // would disable the clear button
  clear: {value: 'something else'} // would work, but return a warning that this is a protected value?
}
```

Alternatively, underscores?

```
sandpit.settings = {
  normalSetting: {value: 'something'},
  _clear: false // would disable the clear button
}
```

**Comment by superhighfives** [comment]
Built with the following settings:

```
sandpit.settings = {
  clear: false,
  reset: false
}
```

It will be ignored (well, used normally) if the value of clear and reset are an option, so it means you couldn't trigger it if you didn't know the API.

Not currently documented, but needs to be.

**Comment by geelen** [comment]
This looks good. `sandpit.settings =` is a fine API, and using `false` in that way is pretty clear

**Comment by superhighfives** [comment]
Awesome. Added to the docs and deployed, so closing!
