### ISSUE TITLE
postinstall breaks new installations

### ISSUE THREAD

**Issue by geelen** [superhighfives/sandpit#34]
`site` isn't shipped to npm because of `.npmignore`, so trying to install sandpit gives you this:

```
error /Users/glen/src/work/unbound/kinetic-logos/node_modules/sandpit: Command failed.
Exit code: 1
Command: sh
Arguments: -c cd site && npm install && cd -
Directory: /Users/glen/src/work/unbound/kinetic-logos/node_modules/sandpit
Output:
sh: line 0: cd: site: No such file or directory
    at SpawnError (/usr/local/lib/node_modules/yarnpkg/lib/errors.js:18:1)
    at ChildProcess.proc.on.code (/usr/local/lib/node_modules/yarnpkg/lib/util/child.js:107:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
info Visit http://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

I was able to install sandpit using `--ignore-scripts` but you might want to release a version of this with this deleted, or at least one that checks if `site` dir is present.

**Comment by superhighfives** [comment]
Yep. I canned it and updated it to:
```"start": "cd site && npm install && npm run start && cd -",```

But that's not really an answer. Would it be better to have a script that says postinstall "if site exists run `cd site && npm install && cd -`"?

**Comment by superhighfives** [comment]
Found a cleaner way of dealing with it:

```
var spawn = require('child_process').spawn
var fs = require('fs')
if (fs.existsSync('site')) {
  spawn('npm', ['install'], {cwd: 'site', stdio: 'inherit'})
} else {
  console.log('postinstall not required - /site not available')
}
```

**Comment by superhighfives** [comment]
Right! Added this to `package.json`
```"postinstall": "node scripts/postinstall"```

Tested and deployed with https://github.com/superhighfives/sandpit/releases/tag/v0.1.4 (I messed up a couple of tags and commits while learning a little more about how `npm version patch` works, so jumping to 0.1.4)
